version: '0.1'

services:
  api:
    build: ./api
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_PORT: ${DATABASE_PORT}
    ports:
      - "8000:8000"

  db:
    build: ./db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"

    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U $POSTGRES_DB"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3
    

# volumes:
#   pgdata:
