INSERT INTO tasks (task_name, is_done) VALUES
('Estudar Teoria da Computação', FALSE),
('Fazer trabalho de Redes', FALSE),
('Apresentação IA', FALSE),
('Ler artigo ML', FALSE),
('Exercícios Álgebra', FALSE),
('Relatório BD', FALSE),
('Pesquisa Sistemas', FALSE),
('Programação em C', FALSE),
('Revisar Estatística', FALSE),
('Estudar SO', FALSE),
('Resumo Engenharia', FALSE),
('Apresentação Segurança', FALSE),
('Exercícios Cálculo', FALSE),
('Estudar Linguagens', FALSE),
('Lógica Matemática', FALSE),
('Apresentação PI', FALSE),
('Experimento Eletrônica', FALSE),
('Ler Sistemas Digitais', FALSE),
('Estudar Física', FALSE),
('Análise Requisitos', FALSE),
('Desenvolver Algoritmo', FALSE),
('Estudar BD', FALSE),
('Pesquisa Computação', FALSE),
('Revisar Sistemas Embarcados', FALSE),
('Exercícios Python', FALSE),
('Revisão Código', FALSE),
('Estudar Redes', FALSE),
('Apresentação VR', FALSE),
('Problemas Geometria', FALSE),
('Experimento Circuitos', FALSE);

INSERT INTO tags (tag_name, task_id) VALUES
('Teoria da Computação', 1),
('Estudo', 1),
('Apresentação', 3),
('Inteligência Artificial', 3),
('Seminário', 4),
('Machine Learning', 4),
('Exercícios', 5),
('Álgebra Linear', 5),
('Relatório', 6),
('Projeto de Banco de Dados', 6),
('Pesquisa', 7),
('Sistemas Distribuídos', 7),
('Programação em C', 8),
('Estatística', 9),
('Sistemas Operacionais', 10),
('Engenharia de Software', 11),
('Segurança da Informação', 12),
('Cálculo Numérico', 13),
('Linguagens de Programação', 14),
('Lógica Matemática', 15),
('Projeto Integrador', 16),
('Laboratório de Eletrônica', 17),
('Sistemas Digitais', 18),
('Física', 19),
('Análise de Requisitos', 20),
('Algoritmos e Estruturas de Dados', 21),
('Banco de Dados', 22),
('Computação Quântica', 23),
('Sistemas Embarcados', 24),
('Python', 25),
('Revisão de Código', 26),
('Redes de Computadores', 27),
('Realidade Virtual', 28),
('Geometria Analítica', 29),
('Laboratório de Circuitos Elétricos', 30);
